/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demotique.form;

import com.demotique.glasspanepopup.GlassPanePopup;
import java.awt.Color;

/**
 *
 * @author MSI LAPTOP
 */
public class Notifications extends javax.swing.JPanel {

    /**
     * Creates new form Notifications
     */
    static int indexcolor;
    public Notifications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item1 = new javax.swing.JPanel();
        note1 = new javax.swing.JLabel();
        notread1 = new com.demotique.swing.win_button.Button();
        jLabel1 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        note2 = new javax.swing.JLabel();
        notread2 = new com.demotique.swing.win_button.Button();
        jLabel2 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        note3 = new javax.swing.JLabel();
        notread3 = new com.demotique.swing.win_button.Button();
        jLabel3 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        note4 = new javax.swing.JLabel();
        notread4 = new com.demotique.swing.win_button.Button();
        jLabel4 = new javax.swing.JLabel();
        item5 = new javax.swing.JPanel();
        note5 = new javax.swing.JLabel();
        notread5 = new com.demotique.swing.win_button.Button();
        jLabel5 = new javax.swing.JLabel();
        item6 = new javax.swing.JPanel();
        note6 = new javax.swing.JLabel();
        notread6 = new com.demotique.swing.win_button.Button();
        jLabel6 = new javax.swing.JLabel();

        setOpaque(false);

        item1.setBackground(new java.awt.Color(3, 0, 21));
        item1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });

        note1.setBackground(new java.awt.Color(0, 0, 0));
        note1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note1.setForeground(new java.awt.Color(255, 255, 255));
        note1.setText("Notification1");

        notread1.setBackground(new java.awt.Color(240, 62, 62));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 229, 229));
        jLabel1.setText("Title: Light Reminder....");

        javax.swing.GroupLayout item1Layout = new javax.swing.GroupLayout(item1);
        item1.setLayout(item1Layout);
        item1Layout.setHorizontalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note1)
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notread1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item1Layout.setVerticalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addGroup(item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note1)
                            .addComponent(jLabel1)))
                    .addGroup(item1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(notread1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        item2.setBackground(new java.awt.Color(3, 0, 21));
        item2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });

        note2.setBackground(new java.awt.Color(0, 0, 0));
        note2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note2.setForeground(new java.awt.Color(255, 255, 255));
        note2.setText("Notification2");

        notread2.setBackground(new java.awt.Color(240, 62, 62));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 229, 229));
        jLabel2.setText("Title: Air Conditioner Reminder....");

        javax.swing.GroupLayout item2Layout = new javax.swing.GroupLayout(item2);
        item2.setLayout(item2Layout);
        item2Layout.setHorizontalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note2)
                .addGap(127, 127, 127)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(notread2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item2Layout.setVerticalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addGroup(item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note2)
                            .addComponent(jLabel2)))
                    .addGroup(item2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(notread2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        item3.setBackground(new java.awt.Color(3, 0, 21));
        item3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });

        note3.setBackground(new java.awt.Color(0, 0, 0));
        note3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note3.setForeground(new java.awt.Color(255, 255, 255));
        note3.setText("Notification3");

        notread3.setBackground(new java.awt.Color(240, 62, 62));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 229, 229));
        jLabel3.setText("Title: Fire Safety Alert....");

        javax.swing.GroupLayout item3Layout = new javax.swing.GroupLayout(item3);
        item3.setLayout(item3Layout);
        item3Layout.setHorizontalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note3)
                .addGap(125, 125, 125)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notread3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item3Layout.setVerticalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addGroup(item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note3)
                            .addComponent(jLabel3)))
                    .addGroup(item3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(notread3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        item4.setBackground(new java.awt.Color(3, 0, 21));
        item4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });

        note4.setBackground(new java.awt.Color(0, 0, 0));
        note4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note4.setForeground(new java.awt.Color(255, 255, 255));
        note4.setText("Notification4");

        notread4.setBackground(new java.awt.Color(240, 62, 62));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 229, 229));
        jLabel4.setText("Title: TV Reminder....");

        javax.swing.GroupLayout item4Layout = new javax.swing.GroupLayout(item4);
        item4.setLayout(item4Layout);
        item4Layout.setHorizontalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note4)
                .addGap(125, 125, 125)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notread4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item4Layout.setVerticalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addGroup(item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note4)
                            .addComponent(jLabel4)))
                    .addGroup(item4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(notread4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        item5.setBackground(new java.awt.Color(3, 0, 21));
        item5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item5MouseClicked(evt);
            }
        });

        note5.setBackground(new java.awt.Color(0, 0, 0));
        note5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note5.setForeground(new java.awt.Color(255, 255, 255));
        note5.setText("Notification5");

        notread5.setBackground(new java.awt.Color(240, 62, 62));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 229, 229));
        jLabel5.setText("Title: Visitor Alert....");

        javax.swing.GroupLayout item5Layout = new javax.swing.GroupLayout(item5);
        item5.setLayout(item5Layout);
        item5Layout.setHorizontalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note5)
                .addGap(125, 125, 125)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notread5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item5Layout.setVerticalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item5Layout.createSequentialGroup()
                .addGroup(item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note5)
                            .addComponent(jLabel5)))
                    .addGroup(item5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(notread5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        item6.setBackground(new java.awt.Color(3, 0, 21));
        item6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item6MouseClicked(evt);
            }
        });

        note6.setBackground(new java.awt.Color(0, 0, 0));
        note6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        note6.setForeground(new java.awt.Color(255, 255, 255));
        note6.setText("Notification6");

        notread6.setBackground(new java.awt.Color(240, 62, 62));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 229, 229));
        jLabel6.setText("Title: Cooling Reminder....");

        javax.swing.GroupLayout item6Layout = new javax.swing.GroupLayout(item6);
        item6.setLayout(item6Layout);
        item6Layout.setHorizontalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(note6)
                .addGap(124, 124, 124)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notread6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        item6Layout.setVerticalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item6Layout.createSequentialGroup()
                .addGroup(item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(item6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(note6)
                            .addComponent(jLabel6)))
                    .addGroup(item6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(notread6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(1));
        item1.setBackground(Color.white);
        notread1.setBackground(Color.GREEN);
        jLabel1.setForeground(Color.BLACK);
        jLabel2.setForeground(new Color(230,229,229));
        jLabel3.setForeground(new Color(230,229,229));
        jLabel4.setForeground(new Color(230,229,229));
        jLabel5.setForeground(new Color(230,229,229));
        jLabel6.setForeground(new Color(230,229,229));
        note1.setForeground(Color.BLACK);
        note2.setForeground(Color.white);
        note3.setForeground(Color.white);
        note4.setForeground(Color.white);
        note5.setForeground(Color.white);
        note6.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(2));
        item2.setBackground(Color.white);
        notread2.setBackground(Color.GREEN);
        jLabel2.setForeground(Color.BLACK);
        jLabel1.setForeground(new Color(230,229,229));
        jLabel3.setForeground(new Color(230,229,229));
        jLabel4.setForeground(new Color(230,229,229));
        jLabel5.setForeground(new Color(230,229,229));
        jLabel6.setForeground(new Color(230,229,229));
        note2.setForeground(Color.BLACK);
        note1.setForeground(Color.white);
        note3.setForeground(Color.white);
        note4.setForeground(Color.white);
        note5.setForeground(Color.white);
        note6.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item2MouseClicked

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(3));
        item3.setBackground(Color.white);
        notread3.setBackground(Color.GREEN);
        jLabel3.setForeground(Color.BLACK);
        jLabel2.setForeground(new Color(230,229,229));
        jLabel1.setForeground(new Color(230,229,229));
        jLabel4.setForeground(new Color(230,229,229));
        jLabel5.setForeground(new Color(230,229,229));
        jLabel6.setForeground(new Color(230,229,229));
        note3.setForeground(Color.BLACK);
        note2.setForeground(Color.white);
        note1.setForeground(Color.white);
        note4.setForeground(Color.white);
        note5.setForeground(Color.white);
        note6.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item1.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(4));
        item4.setBackground(Color.white);
        notread4.setBackground(Color.GREEN);
        jLabel4.setForeground(Color.BLACK);
        jLabel2.setForeground(new Color(230,229,229));
        jLabel3.setForeground(new Color(230,229,229));
        jLabel1.setForeground(new Color(230,229,229));
        jLabel5.setForeground(new Color(230,229,229));
        jLabel6.setForeground(new Color(230,229,229));
        note4.setForeground(Color.BLACK);
        note2.setForeground(Color.white);
        note3.setForeground(Color.white);
        note1.setForeground(Color.white);
        note5.setForeground(Color.white);
        note6.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item1.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item4MouseClicked

    private void item5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item5MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(5));
        item5.setBackground(Color.white);
        notread5.setBackground(Color.GREEN);
        jLabel5.setForeground(Color.BLACK);
        jLabel2.setForeground(new Color(230,229,229));
        jLabel3.setForeground(new Color(230,229,229));
        jLabel4.setForeground(new Color(230,229,229));
        jLabel1.setForeground(new Color(230,229,229));
        jLabel6.setForeground(new Color(230,229,229));
        note5.setForeground(Color.BLACK);
        note2.setForeground(Color.white);
        note3.setForeground(Color.white);
        note4.setForeground(Color.white);
        note1.setForeground(Color.white);
        note6.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item1.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item5MouseClicked

    private void item6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item6MouseClicked
        // TODO add your handling code here:
        GlassPanePopup.showPopup(new Message(6));
        item6.setBackground(Color.white);
        notread6.setBackground(Color.GREEN);
        note6.setForeground(Color.BLACK);
        jLabel6.setForeground(Color.BLACK);
        jLabel2.setForeground(new Color(230,229,229));
        jLabel3.setForeground(new Color(230,229,229));
        jLabel4.setForeground(new Color(230,229,229));
        jLabel5.setForeground(new Color(230,229,229));
        jLabel1.setForeground(new Color(230,229,229));
        note2.setForeground(Color.white);
        note3.setForeground(Color.white);
        note4.setForeground(Color.white);
        note5.setForeground(Color.white);
        note1.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item1.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JPanel item5;
    private javax.swing.JPanel item6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel note2;
    private javax.swing.JLabel note3;
    private javax.swing.JLabel note4;
    private javax.swing.JLabel note5;
    private javax.swing.JLabel note6;
    private com.demotique.swing.win_button.Button notread1;
    private com.demotique.swing.win_button.Button notread2;
    private com.demotique.swing.win_button.Button notread3;
    private com.demotique.swing.win_button.Button notread4;
    private com.demotique.swing.win_button.Button notread5;
    private com.demotique.swing.win_button.Button notread6;
    // End of variables declaration//GEN-END:variables
}
