/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.demotique.form;

import com.demotique.swing.scrollbar.ScrollBarCustom;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author MSI LAPTOP
 */
public class Videos extends javax.swing.JPanel {

    /**
     * Creates new form Form2
     */
    public Videos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoplayer = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        video1 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        video2 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        video3 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        video4 = new javax.swing.JLabel();
        item5 = new javax.swing.JPanel();
        video5 = new javax.swing.JLabel();
        item6 = new javax.swing.JPanel();
        video6 = new javax.swing.JLabel();

        setOpaque(false);

        videoplayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videoplayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/demotique/form/video1.jpg"))); // NOI18N

        item1.setBackground(new java.awt.Color(255, 255, 255));
        item1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });

        video1.setBackground(new java.awt.Color(255, 255, 255));
        video1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video1.setText("Video1");

        javax.swing.GroupLayout item1Layout = new javax.swing.GroupLayout(item1);
        item1.setLayout(item1Layout);
        item1Layout.setHorizontalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item1Layout.setVerticalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item2.setBackground(new java.awt.Color(3, 0, 21));
        item2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });

        video2.setBackground(new java.awt.Color(0, 0, 0));
        video2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video2.setForeground(new java.awt.Color(255, 255, 255));
        video2.setText("Video2");

        javax.swing.GroupLayout item2Layout = new javax.swing.GroupLayout(item2);
        item2.setLayout(item2Layout);
        item2Layout.setHorizontalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(922, Short.MAX_VALUE))
        );
        item2Layout.setVerticalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item3.setBackground(new java.awt.Color(3, 0, 21));
        item3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });

        video3.setBackground(new java.awt.Color(0, 0, 0));
        video3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video3.setForeground(new java.awt.Color(255, 255, 255));
        video3.setText("Video3");

        javax.swing.GroupLayout item3Layout = new javax.swing.GroupLayout(item3);
        item3.setLayout(item3Layout);
        item3Layout.setHorizontalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item3Layout.setVerticalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item4.setBackground(new java.awt.Color(3, 0, 21));
        item4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });

        video4.setBackground(new java.awt.Color(0, 0, 0));
        video4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video4.setForeground(new java.awt.Color(255, 255, 255));
        video4.setText("Video4");

        javax.swing.GroupLayout item4Layout = new javax.swing.GroupLayout(item4);
        item4.setLayout(item4Layout);
        item4Layout.setHorizontalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item4Layout.setVerticalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item5.setBackground(new java.awt.Color(3, 0, 21));
        item5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item5MouseClicked(evt);
            }
        });

        video5.setBackground(new java.awt.Color(0, 0, 0));
        video5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video5.setForeground(new java.awt.Color(255, 255, 255));
        video5.setText("Video5");

        javax.swing.GroupLayout item5Layout = new javax.swing.GroupLayout(item5);
        item5.setLayout(item5Layout);
        item5Layout.setHorizontalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item5Layout.setVerticalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        item6.setBackground(new java.awt.Color(3, 0, 21));
        item6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        item6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item6MouseClicked(evt);
            }
        });

        video6.setBackground(new java.awt.Color(0, 0, 0));
        video6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        video6.setForeground(new java.awt.Color(255, 255, 255));
        video6.setText("Video6");

        javax.swing.GroupLayout item6Layout = new javax.swing.GroupLayout(item6);
        item6.setLayout(item6Layout);
        item6Layout.setHorizontalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(video6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item6Layout.setVerticalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(video6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoplayer, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(videoplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video1.jpg"));
        item1.setBackground(Color.white);
        video1.setForeground(Color.BLACK);
        video2.setForeground(Color.white);
        video3.setForeground(Color.white);
        video4.setForeground(Color.white);
        video5.setForeground(Color.white);
        video6.setForeground(Color.white);
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video2.jpg"));
        item2.setBackground(Color.white);
        video2.setForeground(Color.BLACK);
        video1.setForeground(Color.white);
        video3.setForeground(Color.white);
        video4.setForeground(Color.white);
        video5.setForeground(Color.white);
        video6.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item2MouseClicked

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video3.jpg"));
        item3.setBackground(Color.white);
        video3.setForeground(Color.BLACK);
        video2.setForeground(Color.white);
        video1.setForeground(Color.white);
        video4.setForeground(Color.white);
        video5.setForeground(Color.white);
        video6.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item2.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video4.jpg"));
        item4.setBackground(Color.white);
        video4.setForeground(Color.BLACK);
        video3.setForeground(Color.white);
        video1.setForeground(Color.white);
        video2.setForeground(Color.white);
        video5.setForeground(Color.white);
        video6.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item4MouseClicked

    private void item5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item5MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video5.jpg"));
        item5.setBackground(Color.white);
        video5.setForeground(Color.BLACK);
        video4.setForeground(Color.white);
        video1.setForeground(Color.white);
        video2.setForeground(Color.white);
        video3.setForeground(Color.white);
        video6.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item6.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item5MouseClicked

    private void item6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item6MouseClicked
        // TODO add your handling code here:
        videoplayer.setIcon(new ImageIcon("F:/Demotique/src/com/demotique/icon/video6.jpg"));
        item6.setBackground(Color.white);
        video6.setForeground(Color.BLACK);
        video5.setForeground(Color.white);
        item1.setBackground(new Color(3,0,21));
        item2.setBackground(new Color(3,0,21));
        item3.setBackground(new Color(3,0,21));
        item4.setBackground(new Color(3,0,21));
        item5.setBackground(new Color(3,0,21));
    }//GEN-LAST:event_item6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JPanel item5;
    private javax.swing.JPanel item6;
    private javax.swing.JLabel video1;
    private javax.swing.JLabel video2;
    private javax.swing.JLabel video3;
    private javax.swing.JLabel video4;
    private javax.swing.JLabel video5;
    private javax.swing.JLabel video6;
    private javax.swing.JLabel videoplayer;
    // End of variables declaration//GEN-END:variables
}
